# wandb configuration
project: CORL
group: AWAC-D4RL
name: AWAC
run_id: mps
# environment and dataset
env_name: mujoco/halfcheetah/simple-v0

# network and optimization
hidden_dim: 256
learning_rate: 3e-4 # Scientific notation is supported in YAML
gamma: 0.99
tau: 5e-3
awac_lambda: 1.0
num_train_ops: 1000000
batch_size: 256
buffer_size: 2000000

# training flags and evaluation
normalize_reward: false
eval_frequency: 1000
n_test_episodes: 10

# saving and reproducibility
checkpoints_path: /Users/batin13/Desktop/RL Projects/Trained_Models/checkpoints/
deterministic_torch: false
seed: 42
test_seed: 69
device: mps