# wandb configuration
project: Debug
group: T1
name: Small_updates
run_id: Small_updates_simple_scale_six

# environment and dataset
env_name: mujoco/halfcheetah/simple-v0    #mujoco/halfcheetah/medium-v0 #mujoco/halfcheetah/simple-v0

seed: 42
test_seed: 69
deterministic_torch: false

num_train_ops: 1000000

# Network Architecture Hyperparameters
hidden_dim: 256
num_hidden_layers: 6
buffer_size: 2_000_000
batch_size: 256

# Optimization Hyperparameters
learning_rate: 3e-4
gamma: 0.99
tau: 5e-3
temperature: 1.0

# training flags and evaluation
normalize_reward: false
eval_frequency: 1000
n_test_episodes: 10

# saving and reproducibility
checkpoints_path: "/Users/batin13/Desktop/RL Projects/Trained_Models/checkpoints/"
device: cpu # or 'cuda'

# Otter Agent Hyperparameters (Unpacked via **cfg.agent)
agent:
  gamma: ${gamma}
  tau: ${tau}
  temperature: ${temperature}
  exp_adv_max: 100.0
  fino: false
  flag_type: 'trun'
  flag_threshold: 0.8
  scale_gradient: 6.0
  fino_knob: 0.1

actor: 
  ebm: null
  opt_type: 'nag' # gd or nag
  step_size: 0.01
  num_step: 25
  moment: 0.3